package com.marchenaya.chirp.convention

internal const val IMPLEMENTATION = "implementation"
internal const val TEST_IMPLEMENTATION = "testImplementation"
internal const val DEBUG_IMPLEMENTATION = "debugImplementation"
internal const val CORE_LIBRARY_DESUGARING = "coreLibraryDesugaring"
internal const val ANDROID_MAIN_IMPLEMENTATION = "androidMainImplementation"
internal const val COMMON_MAIN_IMPLEMENTATION = "commonMainImplementation"
internal const val COMMON_TEST_IMPLEMENTATION = "commonTestImplementation"
internal const val COMPOSE_COMPILER_PLUGIN_ID = "org.jetbrains.kotlin.plugin.compose"
internal const val ANDROID_KOTLIN_MULTIPLATFORM_LIBRARY_PLUGIN_ID =
    "com.android.kotlin.multiplatform.library"
internal const val KOTLIN_MULTIPLATFORM_PLUGIN_ID = "org.jetbrains.kotlin.multiplatform"
internal const val KOTLIN_SERIALIZATION_PLUGIN_ID = "org.jetbrains.kotlin.plugin.serialization"
internal const val ANDROID_LINT_PLUGIN_ID = "com.android.lint"
internal const val COMPOSE_PLUGIN_ID = "org.jetbrains.compose"
internal const val LIBRARY_COMPOSE_UI_TOOLING = "jetbrains-compose-ui-tooling"
internal const val LIBRARY_DESUGAR_JDK_LIBS = "android-desugarJdkLibs"
internal const val VERSION_COMPILE_SDK = "projectCompileSdkVersion"
internal const val VERSION_MIN_SDK = "projectMinSdkVersion"